DROP DATABASE IF EXISTS ToDelete;
CREATE DATABASE IF NOT EXISTS DockerMySqlExample;
CREATE USER IF NOT EXISTS 'installer'@'%' IDENTIFIED BY 'N0Pa55wrd';
GRANT ALL ON DockerMySqlExample.* TO 'installer'@'%';
FLUSH PRIVILEGES;
